# Generated by Django 2.2.5 on 2019-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
