# Generated by Django 2.2.5 on 2019-09-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190910_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegister',
            new_name='EventParticipant',
        ),
    ]
