# Generated by Django 2.2.5 on 2019-09-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190907_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventregister',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
