# Generated by Django 2.2.5 on 2019-09-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190911_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='roll_no',
            field=models.CharField(max_length=10),
        ),
    ]
