# Generated by Django 2.2.5 on 2019-10-05 09:24

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190924_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
